### ISSUE TITLE
Stop Command not Processing when other VISCA commands are visible

### ISSUE THREAD

**Issue by Samtastico** [vwout/obs-visca-control#15] opened 2024-01-09 14:15 UTC
This is a very similar issue to those seen in the past but I was unable to find a fix. 
If there are 1 or more Visca Sources visible, the stop function does not work. However if I hide all other Visca sources the stop function will work just fine. g  
For example...  If a preset is a called and completes and then I activate the tilt function, the tilt function will execute but when it is hidden again the stop command will not work.  

Many thanks for all your help and time so far. This is a great script 
![Screenshot 2024-01-09 141431](https://github.com/vwout/obs-visca-control/assets/156094750/040d54d6-f525-4c71-ac46-9459cff4b4e6)

![Church Streaming PC - AnyDesk 09_01_2024 14_02_50](https://github.com/vwout/obs-visca-control/assets/156094750/62266589-69d3-4184-9bd0-b1fe2bc1bbfc)

**Comment by vwout** [comment] 2024-01-10 21:40
Your issue seems to be related to #13. I tried to reproduce it, but I can't so I expect the issue is resolved in commits afbc8b0b and dce5b426. Could you try by updating the files `libvisca.lua` and `obs-visca-control.lua` to the latest version on github?

**Comment by Samtastico** [comment] 2024-01-11 13:32
Yes, I am running the latest version 2.3.1
On a custom Visca Command, **0A 11 54 02 will start** the auto tracking and **0A 11 54 03 is to stop** the auto tracking. If I put them on **separate start commands they work fine** but if I have one on the start command and the other on the stop command then the stop command does not work. 

Hope that helps   

Many thanks

**Comment by vwout** [comment] 2024-01-13 19:14
I released version 2.4 today, this issue should be resolved in that release. In case it is not, or when you experience other issues, please enable 'debug logging' in the script settings, repeat the operation and post the full log here.

**Comment by Samtastico** [comment] 2024-01-15 10:58
Hi, I have updated to 2.4 and this is the error I receive when hiding/showing a source... I do not receive this error on version 2.3.1 but this is the version where the stop command does not execute. 

10:55:05.065: [Lua: obs-visca-control.lua] source_signal_processor (1167): Hide visca source 'Preset 7 (Visca)' (camera 1): no action
10:55:05.066: [Lua: obs-visca-control.lua] source_signal_processor (1167): Deactivate visca source 'Preset 7 (Visca)' (camera 1): process
10:55:05.066: [Lua: obs-visca-control.lua] Failed to call calldata_signal_callback for calldata_signal_callback: [string "C:/Program Files/obs-studio/data/obs-plugins/..."]:1206: table index is nil
10:55:09.032: [Lua: obs-visca-control.lua] source_signal_processor (1167): Show visca source 'Preset 7 (Visca)' (camera 1): no action
10:55:09.032: [Lua: obs-visca-control.lua] source_signal_processor (1167): Activate visca source 'Preset 7 (Visca)' (camera 1): process
10:55:09.665: [Lua: obs-visca-control.lua] do_cam_action_start (563): Start cam 1 action 26 (args direction=0, speed=0, custom_start=table: 0x02898e2d2c50)
10:55:09.736: [Lua: obs-visca-control.lua] ? (528): Connection ERROR received for camera 1 (seq_nr 17): Command not executable
10:55:09.736: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x02898e2ab8a0): 90 60 41 FF

As you can see I am just trying to call a Preset but it is the same if I try any other command. 

Many thanks

**Comment by vwout** [comment] 2024-01-15 18:12
Ah, I think you are not running OBS in Studio mode, so no preview is visible. That explains "table index is nil".
Next to that, your custom stop command for camera 1 does not seem to be supported, but that's not something I can fix for you :)

**Closed as completed** 2024-01-15 18:28 UTC

**Comment by Samtastico** [comment] 2024-01-15 18:34
Hi the command 0A 11 54 03 which I use is definitely valid as when I put it on a custom command on its own it works perfectly. 
Yes, I do not use studio mode. Is there a way to stop the error from popping up each time?

**Comment by vwout** [comment] 2024-01-15 18:40
Camera says no according the log :) It returns Visca error 0x41 ("Command not executable"). That error won't cause a popup and if your commands work, never mind.

The other error ("table index is nil") does cause a popup and is just resolved in the latest code in change (110909d).
