### ISSUE TITLE
Stop Command not triggering 

### ISSUE THREAD

**Issue by Samtastico** [vwout/obs-visca-control#16] opened 2024-01-15 19:58 UTC
Here you will see a custom down command triggering but when the stop command is supposed to be triggered it does not. 

Down tilt command =  01 06 01 01 01 03 02
Stop command = 01 06 01 01 01 03 03

"19:56:40.949: [Lua: obs-visca-control.lua] source_signal_processor (1167): Show visca source 'Down Tilt (Visca)' (camera 1): no action
19:56:40.949: [Lua: obs-visca-control.lua] source_signal_processor (1167): Activate visca source 'Down Tilt (Visca)' (camera 1): process
19:56:40.949: [Lua: obs-visca-control.lua] do_cam_action_start (563): Start cam 1 action 26 (args custom_start=table: 0x021db2829088, speed=0, custom_stop=table: 0x021db2854f18, direction=0)
19:56:41.049: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 112)
19:56:41.049: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x021db27fb7a8): 90 41 FF
19:56:41.149: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 112)
19:56:41.149: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x021db27fb7a8): 90 51 FF
19:56:46.682: [Lua: obs-visca-control.lua] source_signal_processor (1167): Hide visca source 'Down Tilt (Visca)' (camera 1): no action
19:56:46.683: [Lua: obs-visca-control.lua] source_signal_processor (1167): Deactivate visca source 'Down Tilt (Visca)' (camera 1): process
19:56:46.683: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Chapel Wide
19:56:46.683: [Lua: obs-visca-control.lua] camera_active_in_scene (1073): Camera ref: 1 active on program: 1
19:56:46.683: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Chapel Wide
19:56:46.683: [Lua: obs-visca-control.lua] source_signal_processor (1232): Not running stop action for source 'Down Tilt (Visca)', because it is currently active on program" 

Many thanks

**Comment by vwout** [comment] 2024-01-15 21:42
This looks like intended behavior, though influenced by the OBS event scheduler.
You seem to have two scenes, both controlling the same camera.

Scene1: Run tilt command when scene becomes active run stop when it deactivates
Scene2: Zoom out camera

Now when the deactivation command of scene1 would run when scene2 has become active, it could (the script doesn't know what the custom commands mean) immediately stop the camera zoom, since it operates the same camera.

But I'll think of a solution, maybe a checkbox to 'always run stop command' and check whether the event order is different based on when OBS is run in studio mode or not.

**Comment by Samtastico** [comment] 2024-01-15 22:44
I have finally found the issue...

When a Preset is called and is left visible then the stop commands on the other VISCA commands do not run. If you hide the Preset command all the other VISCA Stop commands run.

"
22:42:41.548: [Lua: obs-visca-control.lua] source_signal_processor (1167): Hide visca source 'Preset 1 ' (camera 1): no action

22:42:41.549: [Lua: obs-visca-control.lua] source_signal_processor (1167): Deactivate visca source 'Preset 1 ' (camera 1): process

22:42:41.549: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2

22:42:41.549: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:41.549: [Lua: obs-visca-control.lua] do_cam_action_stop (680): Stop cam 1 action 2 (arg preset=1, speed=0, direction=0)
22:42:43.082: [Lua: obs-visca-control.lua] source_signal_processor (1167): Show visca source 'Preset 1 ' (camera 1): no action
22:42:43.082: [Lua: obs-visca-control.lua] source_signal_processor (1167): Activate visca source 'Preset 1 ' (camera 1): process
22:42:43.082: [Lua: obs-visca-control.lua] do_cam_action_start (563): Start cam 1 action 2 (args preset=1, speed=0, direction=0)
22:42:43.115: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 58)
22:42:43.116: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 41 FF
22:42:44.815: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 58)
22:42:44.815: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 51 FF
22:42:47.515: [Lua: obs-visca-control.lua] source_signal_processor (1167): Show visca source 'Zoom In (Visca)' (camera 1): no action
22:42:47.515: [Lua: obs-visca-control.lua] source_signal_processor (1167): Activate visca source 'Zoom In (Visca)' (camera 1): process
22:42:47.515: [Lua: obs-visca-control.lua] do_cam_action_start (563): Start cam 1 action 4 (args direction=0, speed=0)
22:42:47.615: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 59)
22:42:47.615: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 42 FF
22:42:47.715: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 59)
22:42:47.715: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 52 FF
22:42:50.248: [Lua: obs-visca-control.lua] source_signal_processor (1167): Hide visca source 'Zoom In (Visca)' (camera 1): process
22:42:50.248: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:50.248: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:50.248: [Lua: obs-visca-control.lua] camera_active_in_scene (1073): Camera ref: 1 active on program: 1
22:42:50.249: [Lua: obs-visca-control.lua] source_signal_processor (1232): Not running stop action for source 'Zoom In (Visca)', because it is currently active on program
22:42:50.249: [Lua: obs-visca-control.lua] source_signal_processor (1167): Deactivate visca source 'Zoom In (Visca)' (camera 1): process
22:42:50.249: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:50.249: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:50.249: [Lua: obs-visca-control.lua] camera_active_in_scene (1073): Camera ref: 1 active on program: 1
22:42:50.249: [Lua: obs-visca-control.lua] source_signal_processor (1232): Not running stop action for source 'Zoom In (Visca)', because it is currently active on program
22:42:53.915: [Lua: obs-visca-control.lua] source_signal_processor (1167): Hide visca source 'Preset 1 ' (camera 1): no action
22:42:53.915: [Lua: obs-visca-control.lua] source_signal_processor (1167): Deactivate visca source 'Preset 1 ' (camera 1): process
22:42:53.915: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:53.915: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:53.915: [Lua: obs-visca-control.lua] do_cam_action_stop (680): Stop cam 1 action 2 (arg preset=1, speed=0, direction=0)
22:42:56.048: [Lua: obs-visca-control.lua] source_signal_processor (1167): Show visca source 'Zoom In (Visca)' (camera 1): no action
22:42:56.049: [Lua: obs-visca-control.lua] source_signal_processor (1167): Activate visca source 'Zoom In (Visca)' (camera 1): process
22:42:56.049: [Lua: obs-visca-control.lua] do_cam_action_start (563): Start cam 1 action 4 (args direction=0, speed=0)
22:42:56.115: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 60)
22:42:56.115: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 41 FF
22:42:56.215: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 60)
22:42:56.215: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 51 FF
22:42:57.948: [Lua: obs-visca-control.lua] source_signal_processor (1167): Hide visca source 'Zoom In (Visca)' (camera 1): process
22:42:57.948: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:57.948: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:57.948: [Lua: obs-visca-control.lua] do_cam_action_stop (680): Stop cam 1 action 4 (arg speed=0, direction=0)
22:42:57.949: [Lua: obs-visca-control.lua] source_signal_processor (1167): Deactivate visca source 'Zoom In (Visca)' (camera 1): process
22:42:57.949: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:57.949: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:42:57.949: [Lua: obs-visca-control.lua] do_cam_action_stop (680): Stop cam 1 action 4 (arg speed=0, direction=0)
22:42:58.015: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 61)
22:42:58.015: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 42 FF
22:42:58.115: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 61)
22:42:58.115: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 52 FF
22:42:58.215: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 62)
22:42:58.215: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 41 FF
22:42:58.315: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 62)
22:42:58.315: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 51 FF
22:43:00.448: [Lua: obs-visca-control.lua] source_signal_processor (1167): Show visca source 'Zoom Out (Visca)' (camera 1): no action
22:43:00.448: [Lua: obs-visca-control.lua] source_signal_processor (1167): Activate visca source 'Zoom Out (Visca)' (camera 1): process
22:43:00.448: [Lua: obs-visca-control.lua] do_cam_action_start (563): Start cam 1 action 5 (args direction=0, speed=0)
22:43:00.515: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 63)
22:43:00.515: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 42 FF
22:43:00.615: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 63)
22:43:00.615: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 52 FF
22:43:03.248: [Lua: obs-visca-control.lua] source_signal_processor (1167): Hide visca source 'Zoom Out (Visca)' (camera 1): no action
22:43:03.248: [Lua: obs-visca-control.lua] source_signal_processor (1167): Deactivate visca source 'Zoom Out (Visca)' (camera 1): process
22:43:03.248: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:43:03.249: [Lua: obs-visca-control.lua] camera_active_in_scene (1068): Current program scene is Scene 2
22:43:03.249: [Lua: obs-visca-control.lua] do_cam_action_stop (680): Stop cam 1 action 5 (arg speed=0, direction=0)
22:43:03.315: [Lua: obs-visca-control.lua] ? (524): Connection ACK received for camera 1 (seq_nr 64)
22:43:03.315: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 41 FF
22:43:03.415: [Lua: obs-visca-control.lua] ? (431): Connection Completion received for camera 1 (seq_nr 64)
22:43:03.415: [Lua: obs-visca-control.lua] ? (795): Poll camera 1 (table: 0x01cf5799e618): 90 51 FF
"

**Comment by vwout** [comment] 2024-01-20 20:37
I think I have a solution, as committed in 2e231e2. Just before transitioning a new scene to the program view, so just before executing the start actions, stop actions for cameras that are used in the new scene are executed. This should work on normal and studio mode.

Would you be in the position to test this for your use case?

**Comment by Samtastico** [comment] 2024-01-22 15:10
Hi, so I have tested it in a live environment and the issue still persists. If the call Preset is left active then the stop command on the other VISCA commands will not trigger.

**Comment by vwout** [comment] 2024-01-22 18:15
That's unexpected. How did you update the code? Downloading the latest release or grab the files from GitHub?
To be sure you use the latest, use the following files: [obs-visca-control-beta.zip](https://github.com/vwout/obs-visca-control/files/14013943/obs-visca-control-beta.zip)

If it still does not work, please attach the full log with at least 3 transitions.

**Comment by Samtastico** [comment] 2024-01-23 12:53
Hi, I installed and tested the above linked file however the issue persists. In fact sometimes scenes are deleted and OBS crashes. 

Here is the log file.... The preset called is "P1 (Visa)" 

Here is the log file ... 

12:49:15.035: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'P1 (Visa)' (camera 1): no action
12:49:15.035: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'P1 (Visa)' (camera 1): process
12:49:15.035: [Lua: obs-visca-control.lua] camera_active_in_scene (1080): Current program scene is 'Chapel Wide'
12:49:15.035: [Lua: obs-visca-control.lua] do_cam_action_stop (691): Stop cam 1 action 2 (arg speed=0, direction=0, preset=1)
12:49:15.035: [Lua: obs-visca-control.lua] open_visca_connection (432): Setup new connection for cam 1 at 192.168.110.8:1259
12:49:15.068: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 0)
12:49:15.068: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 50 00 52 FF
12:49:15.901: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'P1 (Visa)' (camera 1): no action
12:49:15.901: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'P1 (Visa)' (camera 1): process
12:49:15.901: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 2 (args direction=0, speed=0, preset=1)
12:49:15.968: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 1)
12:49:15.968: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 42 FF
12:49:20.468: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 1)
12:49:20.468: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 52 FF
12:49:24.935: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'Zoom Out (Visca PTZ)' (camera 1): no action
12:49:24.935: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'Zoom Out (Visca PTZ)' (camera 1): process
12:49:24.935: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 5 (args speed=0, direction=0)
12:49:24.968: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 2)
12:49:24.968: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 41 FF
12:49:25.068: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 2)
12:49:25.068: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 51 FF
12:49:29.535: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'Zoom Out (Visca PTZ)' (camera 1): no action
12:49:29.535: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'Zoom Out (Visca PTZ)' (camera 1): process
12:49:29.535: [Lua: obs-visca-control.lua] camera_active_in_scene (1080): Current program scene is 'Chapel Wide'
12:49:29.535: [Lua: obs-visca-control.lua] camera_active_in_scene (1088): Cam 1 is active in visca action 'P1 (Visa)' on program: Yes
12:49:29.535: [Lua: obs-visca-control.lua] source_signal_processor (1268): Not running stop action for source 'Zoom Out (Visca PTZ)', because its camera (1) is currently active on program
12:49:31.701: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'Zoom In (Visca PTZ)' (camera 1): no action
12:49:31.702: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'Zoom In (Visca PTZ)' (camera 1): process
12:49:31.702: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 4 (args speed=1, direction=0)
12:49:31.768: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 3)
12:49:31.768: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 42 FF
12:49:31.868: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 3)
12:49:31.868: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 52 FF
12:49:34.268: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'Zoom In (Visca PTZ)' (camera 1): no action
12:49:34.268: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'Zoom In (Visca PTZ)' (camera 1): process
12:49:34.269: [Lua: obs-visca-control.lua] camera_active_in_scene (1080): Current program scene is 'Chapel Wide'
12:49:34.269: [Lua: obs-visca-control.lua] camera_active_in_scene (1088): Cam 1 is active in visca action 'P1 (Visa)' on program: Yes
12:49:34.269: [Lua: obs-visca-control.lua] source_signal_processor (1268): Not running stop action for source 'Zoom In (Visca PTZ)', because its camera (1) is currently active on program
12:49:37.130: User switched to scene 'Speaker'
12:49:37.202: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'P1 (Visa)' (camera 1): no action
12:49:37.202: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'P1 (Visa)' (camera 1): process
12:49:37.202: [Lua: obs-visca-control.lua] do_cam_action_stop (691): Stop cam 1 action 2 (arg speed=0, direction=0, preset=1)
12:49:44.535: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'Zoom Out (Visca PTZ)' (camera 1): no action
12:49:44.535: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'Zoom Out (Visca PTZ)' (camera 1): process
12:49:44.536: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 5 (args speed=0, direction=0)
12:49:44.568: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 4)
12:49:44.568: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 41 FF
12:49:44.668: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 4)
12:49:44.669: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 51 FF
12:49:50.568: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'Zoom Out (Visca PTZ)' (camera 1): no action
12:49:50.568: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'Zoom Out (Visca PTZ)' (camera 1): process
12:49:50.568: [Lua: obs-visca-control.lua] do_cam_action_stop (691): Stop cam 1 action 5 (arg speed=0, direction=0)
12:49:50.668: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 5)
12:49:50.668: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 42 FF
12:49:50.768: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 5)
12:49:50.768: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 52 FF
12:49:53.035: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'Zoom In (Visca PTZ)' (camera 1): no action
12:49:53.035: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'Zoom In (Visca PTZ)' (camera 1): process
12:49:53.035: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 4 (args speed=1, direction=0)
12:49:53.068: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 6)
12:49:53.068: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 41 FF
12:49:53.168: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 6)
12:49:53.168: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 51 FF
12:49:54.801: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'Zoom In (Visca PTZ)' (camera 1): no action
12:49:54.802: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'Zoom In (Visca PTZ)' (camera 1): process
12:49:54.802: [Lua: obs-visca-control.lua] do_cam_action_stop (691): Stop cam 1 action 4 (arg speed=1, direction=0)
12:49:54.868: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 7)
12:49:54.868: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 42 FF
12:49:54.968: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 7)
12:49:54.968: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 52 FF
12:49:57.243: User switched to scene 'Conductor'
12:49:57.268: [obs-ndi] ndi_source_shown('Ceiling Mic NDI™ Source'...)
12:49:57.268: [obs-ndi] ndi_source_activated('Ceiling Mic NDI™ Source'...)
12:50:00.969: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'Zoom Out (Visca PTZ)' (camera 1): no action
12:50:00.969: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'Zoom Out (Visca PTZ)' (camera 1): process
12:50:00.970: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 5 (args speed=0, direction=0)
12:50:01.068: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 8)
12:50:01.068: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 42 FF
12:50:01.168: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 8)
12:50:01.168: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 52 FF
12:50:06.868: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'Zoom Out (Visca PTZ)' (camera 1): no action
12:50:06.869: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'Zoom Out (Visca PTZ)' (camera 1): process
12:50:06.869: [Lua: obs-visca-control.lua] do_cam_action_stop (691): Stop cam 1 action 5 (arg speed=0, direction=0)
12:50:06.968: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 9)
12:50:06.968: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 41 FF
12:50:07.068: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 9)
12:50:07.068: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 51 FF
12:50:08.001: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'Zoom In (Visca PTZ)' (camera 1): no action
12:50:08.001: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'Zoom In (Visca PTZ)' (camera 1): process
12:50:08.001: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 4 (args speed=1, direction=0)
12:50:08.068: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 10)
12:50:08.069: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 42 FF
12:50:08.168: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 10)
12:50:08.168: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 52 FF
12:50:10.335: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'Zoom In (Visca PTZ)' (camera 1): no action
12:50:10.335: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'Zoom In (Visca PTZ)' (camera 1): process
12:50:10.335: [Lua: obs-visca-control.lua] do_cam_action_stop (691): Stop cam 1 action 4 (arg speed=1, direction=0)
12:50:10.368: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 11)
12:50:10.368: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 41 FF
12:50:10.468: [Lua: obs-visca-control.lua] ? (442): Connection Completion received for camera 1 (seq_nr 11)
12:50:10.468: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 51 FF
12:50:12.223: User switched to scene 'Speaker'
12:50:12.268: [obs-ndi] ndi_source_hidden('Ceiling Mic NDI™ Source'...)
12:50:12.268: [obs-ndi] ndi_source_deactivated('Ceiling Mic NDI™ Source'...)
12:50:17.832: User switched to scene 'Chapel Wide'
12:50:17.835: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'P1 (Visa)' (camera 1): no action
12:50:17.835: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'P1 (Visa)' (camera 1): process
12:50:17.836: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 2 (args direction=0, speed=0, preset=1)
12:50:17.869: [Lua: obs-visca-control.lua] ? (535): Connection ACK received for camera 1 (seq_nr 12)
12:50:17.869: [Lua: obs-visca-control.lua] ? (806): Poll camera 1 (table: 0x01e911323a10): 90 41 FF
12:50:25.835: [Lua: obs-visca-control.lua] source_signal_processor (1179): Hide visca source 'P1 (Visa)' (camera 1): no action
12:50:25.835: [Lua: obs-visca-control.lua] source_signal_processor (1179): Deactivate visca source 'P1 (Visa)' (camera 1): process
12:50:25.836: [Lua: obs-visca-control.lua] camera_active_in_scene (1080): Current program scene is 'Chapel Wide'
12:50:25.836: [Lua: obs-visca-control.lua] do_cam_action_stop (691): Stop cam 1 action 2 (arg speed=0, direction=0, preset=1)
12:50:26.668: [Lua: obs-visca-control.lua] source_signal_processor (1179): Show visca source 'P1 (Visa)' (camera 1): no action
12:50:26.668: [Lua: obs-visca-control.lua] source_signal_processor (1179): Activate visca source 'P1 (Visa)' (camera 1): process
12:50:26.668: [Lua: obs-visca-control.lua] do_cam_action_start (574): Start cam 1 action 2 (args direction=0, speed=0, preset=1)

**Comment by vwout** [comment] 2024-01-23 22:25
Well, calling a preset does not have a stop action. I do see that you are using zoom in and out, which both have stop actions. It however looks like these are in every scene and also both present in the same scene. The log looks really weird. Maybe this is how it is behaving, but it is very hard to track what's going on in the log without a bit more context.

Deletion of scenes I have never seen happening.

Could you please share:
- (a description of) the configuration of the scenes you are using in the test, so which Visca actions are in which scene - this is part of a full log file
- the **full** log (this log you shared starts in the middle of a transition).

**Comment by Samtastico** [comment] 2024-01-23 22:39
Hi, I will try it on some totally blank scenes with just the other visca commands and the camera feed then report back.

**Comment by vwout** [comment] 2024-01-30 21:31
@Samtastico Have you by any chance been able to test this further?

**Comment by Samtastico** [comment] 2024-01-30 21:35
My apologies, I've been a little snowed under with work but I will make time in the next few days.

**Comment by vwout** [comment] 2024-02-04 21:35
> In fact sometimes scenes are deleted and OBS crashes.

I managed to reproduce your finding. Can't explain it yet, but I will continue debugging.

**Comment by vwout** [comment] 2024-02-05 22:03
I think I found it and fixed it in 46616b6

**Comment by Samtastico** [comment] 2024-02-21 21:15
I will have to make time to check it as I had a scene delete itself during a live event over the weekend.

**Comment by vwout** [comment] 2024-02-22 20:30
Be sure to upgrade to v2.5 before doing any further testing, otherwise you will lose more scenes (because of a bug).

**Closed as completed** 2024-07-11 20:21 UTC
